### ISSUE TITLE
UnexpectedValueException - checksum mismatch

### ISSUE THREAD

**Issue by marcinskubala** [francoispluchino/composer-asset-plugin#100]
Hi, I have problem with installing underscore package. I tried clean-cache command but it didn't help. 

Reading bower.json of bower-asset/underscore (1.8.2)
Reading bower.json of bower-asset/underscore (1.8.1)
Reading bower.json of bower-asset/underscore (1.8.0)
  - Installing npm-asset/underscore (1.8.2)
    Downloading: connection...
    Downloading: 0%
    Downloading: 25%
    Downloading: 45%
    Downloading: 50%
    Downloading: 70%
    Downloading: 95%
    Downloading: 100%

  [UnexpectedValueException]
  phar error: "D:\htdocs\frame\vendor\npm\underscore\5460d52baa0564c2908b5d33
  4ffb984f.tgz" is a corrupted tar file (checksum mismatch of file "DETAR.blo
  cks=8
  /19 NODETAR.depth=1
  24 NODETAR.follow=false
  36 NODETAR.ignoreFiles.0=.npmignore
  36 NODETAR.ignoreFile")

**Comment by francoispluchino** [comment]
Do you use the stable version `1.0.0`?

**Comment by marcinskubala** [comment]
Yes I use stable version "fxp/composer-asset-plugin:1.0.0".

**Comment by francoispluchino** [comment]
You have a `bower-asset/underscore` dependency, but it's the `npm-asset/underscore` dependency that is installed, it's strange... Can you give me your composer.json file?

I just did a test with:

```json
{
    "require": {
        "bower-asset/underscore": "~1.8.2"
    }
}
```

And it's good for me:

```
$ composer install --prefer-dist
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing bower-asset/underscore (1.8.2)
    Downloading: 100%

Writing lock file
Generating autoload files
```

**Comment by marcinskubala** [comment]
Strange, my composer.json file:

```
#!json
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Application Template",
    "keywords": ["yii2", "framework", "advanced", "application template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": "*",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiisoft/yii2-imagine": "*",
        "npm-asset/underscore": "1.8.2"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
```

**Comment by francoispluchino** [comment]
I suggest you to use the Bower dependency with `bower-asset/underscore`, and not NPM (because the support was added for packages with simple dependencies that are not added in the Bower registry).

**Comment by marcinskubala** [comment]
Thanks, the bower-asset/underscore works fine but ultimately I'm trying to install a npm-asset/apidoc package which contains the "npm-asset/underscore" in dependencies. Is there any option to install it?

**Comment by grasmash** [comment]
I've also run into this issue and I've found that I get inconsistent results depending on the machine that I use to download the npm-asset/underscore dependency.

**Comment by grasmash** [comment]
@francoispluchino Could this issue be re-opened? It has not been resolved, as npm-asset/underscore may be define as a requirement for another dependency, causing a failed build.
