### ISSUE TITLE
Incredibly slow on single package update.

### ISSUE THREAD

**Issue by damiandennis** [francoispluchino/composer-asset-plugin#103]
I am only trying to update a single package. i.e

````
composer update codeception/codeception -vvv
````

but when I run this in debug mode as above its doing a check through every npm-asset and every bower-asset and this package has no such dependencies.

````
Adding VCS repository npm-asset/tunnel-agent
Downloading https://api.github.com/repos/mikeal/tunnel-agent
Downloading https://api.github.com/repos/mikeal/tunnel-agent/contents/package.json?ref=master
Downloading https://api.github.com/repos/mikeal/tunnel-agent/commits/master
Downloading https://api.github.com/repos/mikeal/tunnel-agent/tags?per_page=100
Downloading https://api.github.com/repos/mikeal/tunnel-agent/git/refs/heads?per_page=100
Downloading https://registry.npmjs.org/json-stringify-safe
Writing /home/vagrant/.composer/cache/repo/https---registry.npmjs.org/json-stringify-safe-69f9944d225803ac9616178da515b1e9e728d1d8-package.json into cache
Adding VCS repository npm-asset/json-stringify-safe
Downloading https://api.github.com/repos/isaacs/json-stringify-safe
Downloading https://api.github.com/repos/isaacs/json-stringify-safe/contents/package.json?ref=master
Downloading https://api.github.com/repos/isaacs/json-stringify-safe/commits/master
Downloading https://api.github.com/repos/isaacs/json-stringify-safe/tags?per_page=100
Downloading https://api.github.com/repos/isaacs/json-stringify-safe/git/refs/heads?per_page=100
Downloading https://registry.npmjs.org/qs
Writing /home/vagrant/.composer/cache/repo/https---registry.npmjs.org/qs-1100a5d5740e8ce3ac2f5d5e56d4d2551b7499f0-package.json into cache
Adding VCS repository npm-asset/qs
Downloading https://api.github.com/repos/hapijs/qs
Downloading https://api.github.com/repos/hapijs/qs/contents/package.json?ref=master
Downloading https://api.github.com/repos/hapijs/qs/commits/master
Downloading https://api.github.com/repos/hapijs/qs/tags?per_page=100
Downloading https://api.github.com/repos/hapijs/qs/git/refs/heads?per_page=100
Downloading https://registry.npmjs.org/http-signature
Writing /home/vagrant/.composer/cache/repo/https---registry.npmjs.org/http-signature-f9ccbb26acef10b3f113699ffd624ed9048d5352-package.json into cache
````

**Comment by damiandennis** [comment]
Sometimes it takes like 30 minutes to go through all assets which is way to slow when updating a single package.

**Comment by francoispluchino** [comment]
The plugin creates only the VCS repositories automatically. Load all package definitions is a native behavior of Composer, even if you want to update only one package, and unfortunately it's not going to change... (see the various discussions on [composer/composer/issues](https://github.com/composer/composer/issues)).

To reduce the number of requests, I suggest you read : [How to reduce the number of requests for getting the package definitions?](https://github.com/francoispluchino/composer-asset-plugin/blob/1.0/Resources/doc/faqs.md#how-to-reduce-the-number-of-requests-for-getting-the-package-definitions).

**Comment by damiandennis** [comment]
Hmm that seems like you are not even going to try, looking through the code I can see how you could optimize and not do a lookup on every package when updating a single package, maybe I am wrong walking through the steps in xdebug I can see that it is possible with a little bit of work. If I submit a fix will you merge it?

**Comment by damiandennis** [comment]
even an argument to disable your plugin from doing what it does when you know that a package you are updating has no assets. This would save a lot of time on installing packages that do not have any asset dependencies.

**Comment by francoispluchino** [comment]
If you have an optimization, I'm interested, make a PR. Now, there is a cache system, but the requests for getting the list of tags and branches are always executed (native behavior of Composer). Cache this list is problematic, because the VCS repository will get the local version, not the version updated.

**Comment by francoispluchino** [comment]
If I do not include repositories (your deactivation), the Solver SAT will consider that the package should be removed.

**Comment by damiandennis** [comment]
I see what you mean, very restrictive on what a plugin is capable of doing in composer. Especially when its all getters and no setters and the properties are all private or protected.

**Comment by francoispluchino** [comment]
Yes... They do not seek to improve the Solver SAT for VCS Repositories, because the main use is with Packagist or Satis (that directly transmits all configs). Which is not the case for Bower eg, that fully utilizes the analysis of repositories (with GIT), and the registry to only get the URL of the repository.

Given that there is a blockage on this subject with the guys of Composer, I'd rather just have a different approach, which I did not want to initially (using Nodejs, Bower, NPM, and GIT). But I still prefer to wait to start the development of this new version.
