### ISSUE TITLE
Problem with travis-ci automated testing updating assets

### ISSUE THREAD

**Issue by ywarnier** [francoispluchino/composer-asset-plugin#109]
Hi, I'm trying to get my head around this issue for some time now.
We are using composer-asset-plugin to fetch libraries in the Bower list from our project chamilo/chamilo-lms. When running composer update by hand, we sometimes have the following issue:
```
  Problem 1
    - The requested package bower-asset/bootstrap could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package bower-asset/fontawesome could not be found in any version, there may be a typo in the package name.
```
(with more than 10 "problems" in total).

The inconvenience is somewhat reduced here by the use of the composer cache, which is nice.

Our composer.json file used to look like this:
```
        "fxp/composer-asset-plugin": "~1.0",
        "bower-asset/bootstrap": "3.3.*",
        "bower-asset/fontawesome": "4.3.*",
        "bower-asset/moment": "2.9",
        "bower-asset/jquery-ui": "1.11.*",
        "bower-asset/bootstrap-daterangepicker": "1.3.*",
        "bower-asset/ckeditor": "4.4.*",
        "bower-asset/jquery-timeago": "1.4.*",
        "bower-asset/fullcalendar": "2.3.*",
        "bower-asset/mediaelement": "2.16.*",
        "bower-asset/modernizr": "2.8.*",
        "bower-asset/jqueryui-timepicker-addon": "1.5.*",
        "bower-asset/imageMap-resizer": "0.5.3"
```
but reading around, I found that using @stable might help me benefit a little bit more from composer caching (I realize now that because of the versions we mention it's probably useless), so I changed it to this:
```
        "fxp/composer-asset-plugin": "~1.0",
        "bower-asset/bootstrap": "@stable",
        "bower-asset/fontawesome": "@stable",
        "bower-asset/moment": "@stable",
        "bower-asset/jquery-ui": "@stable",
        "bower-asset/bootstrap-daterangepicker": "@stable",
        "bower-asset/ckeditor": "@stable",
        "bower-asset/jquery-timeago": "@stable",
        "bower-asset/fullcalendar": "@stable",
        "bower-asset/mediaelement": "@stable",
        "bower-asset/modernizr": "2.8.*",
        "bower-asset/jqueryui-timepicker-addon": "@stable",
        "bower-asset/imageMap-resizer": "0.5.3"
```

Now the thing is that we use travis-ci.org to run tests on our code, and since about two weeks ago it's been impossible for travis-ci to go further than the composer install step. You can see one of our latest runs to date here: https://travis-ci.org/chamilo/chamilo-lms/jobs/58838471

The issue is the same, only that travis-ci actually launches a new VM (or container) each time it runs the test, so it cannot use Composer caching, and it tries to download all the assets again each time. On a typical day, we will have around 20 pushes to our repo, and travis-ci will launch a new run each time, which I understand might cause the repositories themselves to react by throttling the access, but no composer install has passed in the latest 2 weeks, so I don't think it is about throttling anymore.

I'm thinking we might be forced to use a "trick" of some kind, but I don't want to put all the assets in my repo just to satisfy travis-ci.
Does anyone have a suggestion about what I could do, or can anyone bring some light on what is happening to us?

Thanks

**Comment by francoispluchino** [comment]
It's better to specify the precise stable version (`X.Y.Z`) and not use the `@stable` flag only, because in this case, Composer will get all stable versions for each package (and the plugin will not perform filtering upstream). You can read the FAQs [How to reduce the number of requests for getting the package definitions?](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/faqs.md#how-to-reduce-the-number-of-requests-for-getting-the-package-definitions).

Concerning Travis, it is always recommended to include composer.lock file, to be sure that the version tested on Travis is the same as the local version (meanwhile, a dependence may be updated). In addition, Composer will directly obtain the versions found in the composer.lock file, without performing an analysis.

**Comment by francoispluchino** [comment]
Concerning your first problem, read the FAQs [Composer throws an exception stating that the version does not exist](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/faqs.md#composer-throws-an-exception-stating-that-the-version-does-not-exist).

**Comment by cebe** [comment]
@ywarnier you should install the composer asset plugin in .travis.yml:
https://github.com/chamilo/chamilo-lms/blob/1.10.x/.travis.yml#L16
add this before you do composer install:

	composer global require "fxp/composer-asset-plugin:1.0.0"

**Comment by ywarnier** [comment]
Great, thank you @cebe. The global installation trick worked for travis-ci!

**Comment by francoispluchino** [comment]
@ywarnier Is that this issue can be closed?

**Comment by ywarnier** [comment]
Yes, thank you. I didn't realize I could close it myself, ups. Here you go
