### ISSUE TITLE
Is it possible to hack?

### ISSUE THREAD

**Issue by githubjeka** [francoispluchino/composer-asset-plugin#111]
Now, many packages are arranged in bower.io(npmjs) and in https://packagist.org (here and there).
Index for bower packages too slow. Perhaps not build an index on Bower.io, and transfer to extraction on packagist.org.

Is it possible?

**Comment by francoispluchino** [comment]
Alas, it's not possible, and it's not recommended to merge the two registries. To build an index of over 86,000 repositories, we must regularly analyze all repositories, and and the limit of number of API request for Github will very quickly exceeded (5 000/hours with token)...

An optimization must be performed in the `RemoteFileSystem` of Composer (composer/composer#3282), but it's not on the agenda yet. If performance is very important to you, I suggest you use Bower directly, for the moment.
