### ISSUE TITLE
fatal: Unable to find remote helper for 'git+https'

### ISSUE THREAD

**Issue by damiandennis** [francoispluchino/composer-asset-plugin#112]
Currently getting this error when running an update: 
```
fatal: Unable to find remote helper for 'git+https'
```
its coming from this npm: https://registry.npmjs.org/jsdom which is a dependency on jquery.
this is also a dependency on the yii project and I am unable to change the repo.
I tried it using npm and it works fine.
https://docs.npmjs.com/cli/install refers to git+https as valid.

**Comment by alexandernst** [comment]
I'm getting this for `angular-toastr` in npmjs.com.

**Comment by alexandernst** [comment]
Got it! It turns out I was using the assets plugin in a wrong way. Check [this](http://stackoverflow.com/questions/30128665/unable-to-find-remote-helper-for-githttps/30195382#30195382)

Anyways, maybe this plugin should handle such situations.

**Comment by francoispluchino** [comment]
`git+https` format is not supported actually. But, yes, we should support this repository type.

**Comment by alexandernst** [comment]
@francoispluchino I'm willing to give this a shot, if you think it's not hard to implement. What is required for this to get implemented? Can you give me any tips/guiding?

**Comment by francoispluchino** [comment]
It goes here:
- `Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository::createVcsRepositoryConfig()`
- `Fxp\Composer\AssetPlugin\Repository\NpmRepository::createVcsRepositoryConfig()`

**Comment by francoispluchino** [comment]
Fixed by #128.

**Comment by Geoide** [comment]
I can´t install gulp via composer:
```
require{
...
"npm-asset/gulp": ">=3.9.0"
```

I get the same error:

```
fatal: Unable to find remote helper for 'git+https'
```

**Comment by YasserHassan** [comment]
@Geoide use the development branch to get over this until version 1.0.3 is released.

**Comment by Geoide** [comment]
@YasserHassan I've installed dev branch:
```
composer global require "fxp/composer-asset-plugin:@dev"
```
but it not works. Same message with gulp.
