### ISSUE TITLE
extra/asset-repositories ignored?

### ISSUE THREAD

**Issue by wangchj** [francoispluchino/composer-asset-plugin#113]
Why am I getting the following error when I run `composer update`?

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/datejs could not be found in any version, there may be a typo in the package name.
```

The following is my `composer.json`

```
{
    "name": "My App",
    "description": "My App",
    "type": "project",
    "license": "BSD-3-Clause",
    "require": {
        "bower-asset/sortable": "*",
        "bower-asset/datejs": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        },
        "asset-repositories": [
            {
                "name": "bower-asset/sortable", 
                "type": "bower-github",
                "url": "https://github.com/RubaXa/Sortable.git"
            },
            {
                "name": "bower-asset/datejs",
                "type": "bower-vcs",
                "url": "https://github.com/wangchj/Datejs.git"
            }
        ]
    }
}
```

**Comment by francoispluchino** [comment]
You can find more details in the FAQ: [Composer throws an exception stating that the version does not exist](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/faqs.md#composer-throws-an-exception-stating-that-the-version-does-not-exist).

**Comment by francoispluchino** [comment]
You can check your asset-repositories if they are really used with the `-v` command option.

**Comment by wangchj** [comment]
I used `composer -vvv update` and it appear that composer is downloading from the correct repository. I wonder if there is something wrong with `bower.json` of the Datejs repository, which is below.

```
{
    "name": "Datejs",
    "description": "Datejs is an open source JavaScript Date library for parsing, formatting and processing.",
    "version": "1.0.0-Alpha.1",
    "ignore": [
        "test",
        "src"
    ]
}
```

**Comment by francoispluchino** [comment]
Are you using the latest stable version (`1.0.1`) of the plugin?

**Comment by wangchj** [comment]
I checked `~/.composer/composer.json` it appears that I am using version `fxp/composer-asset-plugin 1.0.0`. Can I modify this file and run an update to get the latest version?

**Comment by francoispluchino** [comment]
You can use this command:

```
composer global require fxp/composer-asset-plugin:1.0.1
```

**Comment by wangchj** [comment]
I update the plugin and still getting the same error.

**Comment by francoispluchino** [comment]
Have you tested the solution in the FAQ: [Composer throws an exception stating that the version does not exist](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/faqs.md#composer-throws-an-exception-stating-that-the-version-does-not-exist)?

**Comment by wangchj** [comment]
Yes:
For option 1 which is just remove `app/vendor` and ran update. Didn't work.
For option 2, I don't think I have any import filter in the `extra` section, but I added the following:
```
{
    "extra": {
        "asset-optimize-with-installed-packages": false
    }
}
```
I didn't try option 3 because I don't know what is the root Composer package.

**Comment by francoispluchino** [comment]
The composer.json file of your project.

**Comment by wangchj** [comment]
For option 3, "bower-asset/datejs" was already in the `require` section in the `composer.json` of my project, and I added `"asset-optimize-with-conjunctive": false` to the `extra` section. Datejs doesn't have dependencies.

**Comment by francoispluchino** [comment]
I just test again, but adding your repository, because there is another package with the same name. And I see that there is no version `stable`, `beta`, `alpha` (in tags). In this case, you must put the flag `@dev` or directly use the development branch `dev-master` (this is the standard behavior of Composer).

```json
{
    "require": {
        "bower-asset/datejs": "@dev"
    },
    "extra": {
        "asset-repositories": [
            {
                "name": "bower-asset/datejs",
                "type": "bower-vcs",
                "url": "https://github.com/wangchj/Datejs.git"
            }
        ]
    }
}
```

**Comment by wangchj** [comment]
I see because there is another Bower package with the same name, there is no way I can use my repository without `@dev` as version, even I have an `alpha` tag in my repository, which I have added.

**Comment by francoispluchino** [comment]
For your tags, you must used the semver format (http://semver.org), and therefore, for your package: `v1.0.0-alpha.1` and not `alpha-1`.

In your composer.json file, the minmum flag are required, by default, it's the flag `@stable`.

In your root composer.json file, you can use `minimum-stability` and `prefer-stable` properties (https://getcomposer.org/doc/04-schema.md#minimum-stability) to avoid always to put the flag for each dependency, but it's always recommended to keep the `minimum-stability` to `stable`.

**Comment by wangchj** [comment]
I updated the tag in my git repository to `1.0.0-alpha.1` and it's now working. Maybe we should add to the documentation of this plug-in that the tags are required. Thank you so much for the help. Btw, what does `fxp` stand for?

**Comment by francoispluchino** [comment]
Sorry, I didn't understand your last question. Want to know the meaning of ‘FXP‘?

**Comment by wangchj** [comment]
When installing the plugin, we have to run `composer global require fxp/composer-asset-plugin:1.0.1`. I'm just curious what fxp is.

**Comment by francoispluchino** [comment]
Ok, no problem! It's that simple, it's my initials: François Xavier Pluchino

**Comment by wangchj** [comment]
That makes sense. Thanks.

**Comment by francoispluchino** [comment]
Is what we can close this issue?

**Comment by wangchj** [comment]
I've created a pull request for this for documentation change.
