### ISSUE TITLE
Add service locater for configuration.

### ISSUE THREAD

**Issue by SamMousa** [francoispluchino/composer-asset-plugin#117]
Currently it is hard for third party code to locate the directory where assets are stored.

If my composer packge which uses a bower package is included by another composer package, how can I determine where my assets will be?

It would be great if we could determine the asset location from within PHP (efficiently).

Some possible solutions that come to mind:
- Create a php file that is added to the composer include that creates a class / constant allowing us to find the bower / npm asset directories.
- Modify the dynamic composer autoloader init class and add the information there.

In any case it would be good if we did not have to parse the composer.json file since that is not something we want for each request.

**Comment by francoispluchino** [comment]
I developed a component and a Symfony2 Bundle to solve this problem:
- [fxp/require-asset](https://github.com/francoispluchino/fxp-require-asset)
- [fxp/require-asset-bundle](https://github.com/francoispluchino/FxpRequireAssetBundle)

**Comment by SamMousa** [comment]
It looks good, but often a lot of frameworks have their asset managers already.
Also this looks overkill for someone who just wants to know where the asset files are being copied to, right?

According to the documentation for require-asset there still needs to be configuration set. (There are things in the docs like __DIR__ . '/vendor')
But if my library is not the root composer package I will not know what the vendor directory is, let alone where the asset directory is.

**Comment by francoispluchino** [comment]
It is true that the component is too evolved to simply retrieve the packages directory.
For Symfony2, there are compiler passes, to automatically configure each package for Assetic. However, I have not extracted the functionality you need.

Small precision, this component is not a package manager (ex. Assetic) but an helper to configure specifically the Assetic (and includes functionalities for Twig).

Your feature should be an independent component of the plugin Composer, that you may develop for example, but indeed, my component included too many features, and it might be interesting to extract this feature in a dedicated component.
