### ISSUE TITLE
NPM registry via proxy

### ISSUE THREAD

**Issue by meteocontrol** [francoispluchino/composer-asset-plugin#118]
We are using the plugin within a docker container which requires a proxy to get access to the internet. This results in 404 errors when trying to download NPM assets. Our workaround is to replace the protocoll in the URL within `NpmRepository.php` with `http://` ([similar to this] (http://stackoverflow.com/questions/11773509/npm-behind-a-proxy-fails-with-status-403))

Would it be possible to introduce an option within `composer.json` to either set the URL or enable/disable SSL for the registries?

**Comment by francoispluchino** [comment]
This functionality is not related to the plugin, but Composer. I never tested with a Proxy, but I suggest you look at the doc of Composer for [Proxy](https://getcomposer.org/doc/03-cli.md#http-proxy-or-http-proxy). Hope this can help you.

**Comment by meteocontrol** [comment]
Thanks for your answer. Adding `registry.npmjs.org` to the `no_proxy` variable had the same effect. I'll have to see if this is a viable option for us, but thanks nonetheless!

**Comment by francoispluchino** [comment]
The plugin simply create VCS Repositories, it connects on the registries of NPM and Bower, but also the URLs (API Github for example) for each repository. I do not know if you need to add them anyway.

After you can force Composer to use the Sources with the option `--prefer-source`, in this way, Composer will use GIT preferably, if it available.

If you find the solution, made me a feedback. I will include in the doc (or make a PR directly, if you prefer).

**Comment by meteocontrol** [comment]
We are actually using the plugin with Satis, so we can't use that option. Furthermore using `no_proxy` could be problematic in the future as our servers require a proxy to communicate with the internet.
