### ISSUE TITLE
FXP doesn't understand recursive dependencies

### ISSUE THREAD

**Issue by alexandernst** [francoispluchino/composer-asset-plugin#125]
I'm trying to install `jsonpath: 0.1.5`, but I'm getting this error:

    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - npm-asset/static-eval 0.2.3 requires npm-asset/escodegen ~0.0.24 -> satisfiable by npm-asset/escodegen[0.0.24, 0.0.25, 0.0.26, 0.0.27, 0.0.28].
        - npm-asset/escodegen 0.0.24 requires npm-asset/esprima ~1.0.2 -> satisfiable by npm-asset/esprima[1.0.2, 1.0.3, 1.0.4].
        - npm-asset/escodegen 0.0.25 requires npm-asset/esprima ~1.0.2 -> satisfiable by npm-asset/esprima[1.0.2, 1.0.3, 1.0.4].
        - npm-asset/escodegen 0.0.26 requires npm-asset/esprima ~1.0.2 -> satisfiable by npm-asset/esprima[1.0.2, 1.0.3, 1.0.4].
        - npm-asset/escodegen 0.0.27 requires npm-asset/esprima ~1.0.2 -> satisfiable by npm-asset/esprima[1.0.2, 1.0.3, 1.0.4].
        - npm-asset/escodegen 0.0.28 requires npm-asset/esprima ~1.0.2 -> satisfiable by npm-asset/esprima[1.0.2, 1.0.3, 1.0.4].
        - Can only install one of: npm-asset/esprima[1.2.2, 1.0.2].
        - Can only install one of: npm-asset/esprima[1.2.2, 1.0.3].
        - Can only install one of: npm-asset/esprima[1.2.2, 1.0.4].
        - npm-asset/jsonpath 0.1.5 requires npm-asset/esprima 1.2.2 -> satisfiable by npm-asset/esprima[1.2.2].
        - npm-asset/jsonpath 0.1.5 requires npm-asset/static-eval 0.2.3 -> satisfiable by npm-asset/static-eval[0.2.3].
        - Installation request for npm-asset/jsonpath 0.1.5 -> satisfiable by npm-asset/jsonpath[0.1.5].

While NPM's output is:

    jsonpath@0.1.5 node_modules/jsonpath
    ├── underscore@1.7.0
    ├── esprima@1.2.2
    ├── static-eval@0.2.3 (escodegen@0.0.28)
    └── jison@0.3.10 (reflect@0.0.7, nomnom@0.4.3, JSONSelect@0.4.0)

If I understand correctly both outputs, FXP is tryiing to install `esprima ~1.0.2` at the same level where all other dependencies are, while NPM is installing `esprima 1.2.2` on the root level of `node_modules` and `esprima ~1.0.2` in the `node_modules` of `escodegen`. Is that right?

If so, is that a bug in FXP? @francoispluchino

**Comment by francoispluchino** [comment]
Recursive dependencies (with multiple dependency for the same package but with a different version) is not supported by Composer, so, by this plugin. Bower has not this problem.
