### ISSUE TITLE
separate frontend and backend packages into "require" and "require-frontend"

### ISSUE THREAD

**Issue by Zauberfisch** [francoispluchino/composer-asset-plugin#127]
I love this plugin, because I can use one package manager for all my dependencies.

While I don't like using multiple package mangers, I would still like some sort of separation between my frontend and my php dependencies.

So, I would like to propose to put dependencies managed by this plugin into its own section.
for example `require` and `require-frontend` or perhaps even better `require`, `require-bower` and `require-npm`.

I am not sure how easy it is to implement such a change, or if at all possible. But if possible, it might even bring "backwards compatibility" (at least to some point) as a side effect. Automated php unit tests might not care about frontend dependencies at all, and could then setup the project to test it without the need for this plugin. It would also help those that committed frontend dependencies into vcs.
(If not possible as own `require` section, perhaps it works inside `extras`)

Additionally, this will make it possible to introduce a `--no-frontend` (or `-no-bower` & `-no-npm`) parameter just like `--no-dev` to allow us to specify if we want to update frontend dependencies

**Comment by francoispluchino** [comment]
This is not possible because the plugin only does create VCS Repositories with the converted informations from Bower or NPM.
