### ISSUE TITLE
remove partial ignored directory

### ISSUE THREAD

**Issue by dizews** [francoispluchino/composer-asset-plugin#130]
Hello.

I think plugin do not undestand ignore paths with subdirectory.
For example:
in "jquery", plugin remove all "dist" directory instead of "dist/cdn"

**Comment by francoispluchino** [comment]
For jquery, only stable versions have a dist directory.

**Comment by dizews** [comment]
I try to use make composer-mirror throw satis. In satis config I use "bower-asset/jquery": ">=1.7@stable", but the result package have not dist files only for jquery. for example "bower-asset/bootstrap" has dist directory.

**Comment by dizews** [comment]
composer/cache has package with dist directory but installed package has not

**Comment by francoispluchino** [comment]
The differnce between bootstrap and jquery, is that the Bootstrap branches contain the distdirectory, whereas this is not the case for jquery. Tags only contain this directory... (it is the choice of the developers).

- [Jquery Branch Master](https://github.com/jquery/jquery)
- [Jquery Tag 2.1.4](https://github.com/jquery/jquery/tree/7751e69b615c6eca6f783a81e292a55725af6b85)

**Comment by francoispluchino** [comment]
composer/cache?

**Comment by dizews** [comment]
~/.composer/cache/files/bower-asset/jquery/7751e69b615c6eca6f783a81e292a55725af6b85.zip - it a cache for jquery 2.1.4

**Comment by francoispluchino** [comment]
Ok, I thought of a package name ... Strange, I use jquery with my composer plugin, and I don't have this bug.

Do you used the last stable version of my plugin (1.0.2) and last `dev` version of Composer?

**Comment by francoispluchino** [comment]
You always have the ability to disable or change the configuration for removing the ignored files of Bower, see the doc [Disable or replace the deleting of the ignore files for Bower](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md#disable-or-replace-the-deleting-of-the-ignore-files-for-bower).

**Comment by dizews** [comment]
I find out why the dist was removed. It is not a bug of you plugin.
thanks for your attention.
