### ISSUE TITLE
provide/replace/conflict support

### ISSUE THREAD

**Issue by nazar-pc** [francoispluchino/composer-asset-plugin#132]
I'm trying to integrate this awesome plugin into my CMS.
It comes with some components already bundled (jQuery, Polymer, UIkit, etc.), but since they are not installed via this plugin I need to prevent duplicated installation to avoid conflicts.

In my case `composer.json` is generated on-fly, I've tried two forms, in both cases jQuery was installed:(

First:
```json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "modules/WebSockets",
                "version": "0.31.0+build-49",
                "require": {
                    "bower-asset/jquery": "^2.1",
                    "bower-asset/bootstrap": "^3"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "plugins/Composer_assets",
                "version": "0.1.0+build-1",
                "require": {
                    "fxp/composer-asset-plugin": "^1.0.2",
                    "oyejorge/less.php": "~1.7",
                    "leafo/scssphp": "^0.1.7"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                },
                "provide": {
                    "bower-asset/jquery": "3.0.0-alpha",
                    "npm-asset/jquery": "3.0.0-alpha",
                    "bower-asset/polymer": "0.5.5",
                    "npm-asset/polymer": "0.5.5",
                    "bower-asset/uikit": "2.21",
                    "npm-asset/uikit": "2.21",
                    "bower-asset/webcomponentsjs": "0.7.3",
                    "npm-asset/webcomponentsjs": "0.7.3",
                    "bower-asset/webcomponents.js": "0.7.3",
                    "npm-asset/webcomponents.js": "0.7.3",
                    "bower-asset/jsSHA": "1.6.1",
                    "npm-asset/jsSHA": "1.6.1",
                    "bower-asset/jssha": "1.6.1",
                    "npm-asset/jssha": "1.6.1"
                }
            }
        }
    ],
    "require": {
        "modules/WebSockets": "0.31.0+build-49",
        "plugins/Composer_assets": "0.1.0+build-1"
    }
}
```
Second:
```json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "modules/WebSockets",
                "version": "0.31.0+build-49",
                "require": {
                    "bower-asset/jquery": "^2.1",
                    "bower-asset/bootstrap": "^3"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "plugins/Composer_assets",
                "version": "0.1.0+build-1",
                "require": {
                    "fxp/composer-asset-plugin": "^1.0.2",
                    "oyejorge/less.php": "~1.7",
                    "leafo/scssphp": "^0.1.7"
                },
                "dist": {
                    "url": "/web/cscms.org/www/components/modules/Composer/empty.zip",
                    "type": "zip"
                }
            }
        }
    ],
    "require": {
        "modules/WebSockets": "0.31.0+build-49",
        "plugins/Composer_assets": "0.1.0+build-1"
    },
    "provide": {
        "bower-asset/jquery": "3.0.0-alpha",
        "npm-asset/jquery": "3.0.0-alpha",
        "bower-asset/polymer": "0.5.5",
        "npm-asset/polymer": "0.5.5",
        "bower-asset/uikit": "2.21",
        "npm-asset/uikit": "2.21",
        "bower-asset/webcomponentsjs": "0.7.3",
        "npm-asset/webcomponentsjs": "0.7.3",
        "bower-asset/webcomponents.js": "0.7.3",
        "npm-asset/webcomponents.js": "0.7.3",
        "bower-asset/jsSHA": "1.6.1",
        "npm-asset/jsSHA": "1.6.1",
        "bower-asset/jssha": "1.6.1",
        "npm-asset/jssha": "1.6.1"
    }
}
```

Is there any possibility to explain that jQuery is already installed or provided by some other package, and do not even download it, just ignore from the beginning?
I'm using version `1.0.2`.

**Comment by francoispluchino** [comment]
Bower and NPM are two separate systems, so it is normal that you have jquery installed 2 times, once for NPM, and another time for Bower.

**Comment by nazar-pc** [comment]
Looks like you didn't understand what I mean.
I've specified that jQuery is already installed:
```json
    "provide": {
        "bower-asset/jquery": "3.0.0-alpha",
        "npm-asset/jquery": "3.0.0-alpha",
```
But anyway it was installed additionally via Bower by dependencies, I want to account at least this simple case when situation is quite obvious.
It seems to be a bug in dependencies resolution process.

**Comment by francoispluchino** [comment]
I probably have not understood your problem ... and I still don't understand it.

The plugin solves nothing, It's the Solver SAT of Composer that makes the analysis. The plugin simply gets the URL via the NPM and Bower registries, and it creates the package for each repository. Basically, it simulates the presence of a file package.json, and creates a VCS Repository automatically. That is what do the plugin.

You talk about Bower, So if I understand correctly, you install Jquery with Bower, but jquery is also installed by the Composer plugin. Is that right? In this case, it's normal.

**Comment by nazar-pc** [comment]
Not exactly.
I know, that in environment where everything is installed jQuery is already present (manually, without package managers, it is just present).
That is why I want to avoid duplicated installation.
For this reason I've added lines:
```json
    "provide": {
        "bower-asset/jquery": "3.0.0-alpha",
        "npm-asset/jquery": "3.0.0-alpha",
```
with the hope that solver will see in case when some package depends on `bower-asset/jquery` (just `jquery` in Bower terms), `jquery` will be skipped from installation as already present.

This works fine for Composer packages, but conflicts have no effect on Bower and/or NPM decisions.

**Comment by francoispluchino** [comment]
If you have a technical solution to achieve what you want, I am open to any proposal.

**Comment by nazar-pc** [comment]
I'm not sure how exactly this plugin integrates with Composer currently.
Who manages dependencies resolution, do you feed everything to Composer or do that for Bower and NPM separately inside plugin alone?

If Composer's dependency resolution system would have all information, it would work already. If plugin does this by itself - than it should read `provide/replace/conflict` fields in addition to `require`, convert them into Bower/NPM format and use them in resolution process.

**Comment by cebe** [comment]
> I've specified that jQuery is already installed:

shouldn't that provide definition go into the root of your composer.json instead of the repository part?

**Comment by nazar-pc** [comment]
Why? It might be part of any package. Also I've tried to put it into root of `composer.json` (look at second part of first message), it didn't work either.

**Comment by cebe** [comment]
> "bower-asset/jquery": "3.0.0-alpha", "npm-asset/jquery": "3.0.0-alpha",

The problem here seems to be that you provide jquery of version 3.0.0-alpha, which does not match the requirement of the first package so another one gets installed.
I played around a bit and found that only `replace` works and only if you put it in the root:

As far as I see this is solely related to composer and not the asset plugin.

```
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "plugins/Composer_assets",
                "version": "0.1.0+build-1",
                "require": {
                    "fxp/composer-asset-plugin": "^1.0.2",
                    "oyejorge/less.php": "~1.7",
                    "leafo/scssphp": "^0.1.7"
                },
                "dist": {
                    "url": "/tmp/composer/empty.zip",
                    "type": "zip"
                }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "modules/WebSockets",
                "version": "0.31.0+build-49",
                "require": {
                    "bower-asset/jquery": "^2.1",
                    "bower-asset/bootstrap": "^3"
                },
                "dist": {
                    "url": "/tmp/composer/empty.zip",
                    "type": "zip"
                }
            }
        }
    ],
    "require": {
        "modules/WebSockets": "0.31.0+build-49",
        "plugins/Composer_assets": "0.1.0+build-1"
    },
	"replace": {
		"bower-asset/jquery": "*",
		"npm-asset/jquery": "*",
		"bower-asset/polymer": "0.5.5",
		"npm-asset/polymer": "0.5.5",
		"bower-asset/uikit": "2.21",
		"npm-asset/uikit": "2.21",
		"bower-asset/webcomponentsjs": "0.7.3",
		"npm-asset/webcomponentsjs": "0.7.3",
		"bower-asset/webcomponents.js": "0.7.3",
		"npm-asset/webcomponents.js": "0.7.3",
		"bower-asset/jsSHA": "1.6.1",
		"npm-asset/jsSHA": "1.6.1",
		"bower-asset/jssha": "1.6.1",
		"npm-asset/jssha": "1.6.1"
	}
}
```

**Comment by nazar-pc** [comment]
> The problem here seems to be that you provide jquery of version 3.0.0-alpha, which does not match the requirement of the first package so another one gets installed.

Normally it should cause dependencies resolution problem and result in error since composer doesn't allow two packages with the same name to be installed, isn't it?

Also look at https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md#usage-with-multiple-versions-of-the-same-dependency

But whose bug is that?

**Comment by cebe** [comment]
> But whose bug is that?

if you can reproduce it without having the asset plugin installed it is a composer issue, otherwise we need to look where the issue is when the plugin is installed.

**Comment by francoispluchino** [comment]
@nazar-pc Can this question be closed?

**Comment by nazar-pc** [comment]
@francoispluchino, I didn't check what @cebe recommended yet, let me try that first.

**Comment by nazar-pc** [comment]
Seems to be Composer issue, reported as https://github.com/composer/composer/issues/4334
