### ISSUE TITLE
Deprecation Notice: Composer\Package\Version\VersionParser::parseLinks is deprecated. Use \Composer\Package\Loader\ArrayLoader::parseLinks() instead in phar:///usr/local/bin/composer/src/Composer/Package/Version/VersionParser.php:226

### ISSUE THREAD

**Issue by kavitama** [francoispluchino/composer-asset-plugin#135]
This is what I get after:
composer global require "fxp/composer-asset-plugin:~1.0.2"
and a composer update.

What is happening, since even if I get back there is no chance to fix it?????

**Comment by francoispluchino** [comment]
Thanks to see the issues before add a new duplicated issue :-). See #133.

**Comment by kavitama** [comment]
Sorry for not checking it before.
I have not understood what is the solution, would you help me in understanding?

**Comment by cornernote** [comment]
run `composer global update`
