### ISSUE TITLE
Can't make it work, maybe some example ?

### ISSUE THREAD

**Issue by talyssonoc** [francoispluchino/composer-asset-plugin#136]
My `composer.json` is like this right now:

```json
{
    "name": "talyssonoc/my-package",
    "description": "  ",
    "require": {
        "fxp/composer-asset-plugin": "~1.0",
        "npm-asset/bootstrap": "dev-master"
    },
    "license": "MIT",
    "minimum-stability": "dev"
}
```

But when I run `composer install`, I get:

```
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package npm-asset/bootstrap could not be found in any version, there may be a typo in the package name.
```

Am I doint something wrong ? Could you write some examples of how to use it ? Thanks !

**Comment by francoispluchino** [comment]
The plugin must be installed in `global` mode and not in `project` mode.

**Comment by talyssonoc** [comment]
Thanks, it's working now ! I was confused because it is said the two ways here: https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md#installation

If some project will require my package in the future, it must also have it installed globally when installing its dependencies ?

**Comment by francoispluchino** [comment]
Yes... see #7.

**Comment by talyssonoc** [comment]
Well...I hope Composer approve this PR soon. Is there some way I can require it globally on my `composer.json` ?

**Comment by francoispluchino** [comment]
Alas, I don't think... And no, you can't require a global plugin (it was a proposal in this PR for Composer).

**Comment by talyssonoc** [comment]
Gonna use it like this them, no problem. It is not capable of using `git+https` helper yet, right ?

**Comment by francoispluchino** [comment]
It must be functional for the `dev-master` branch, but it seems that there is a bug.

**Comment by talyssonoc** [comment]
I see... well, thank you anyway. Great package, btw !
