### ISSUE TITLE
Error trying to resolve dependencies

### ISSUE THREAD

**Issue by jonag** [francoispluchino/composer-asset-plugin#138]
I am trying to use this plugin instead of bower and I'm facing an issue. Here is my composer.json :

    // ...
    "require": {
         // ...
        "bower-asset/bootstrap": "~3.3.4",
        "bower-asset/bootstrap-tokenfield": "~0.12.1",
        // ..
    },
    // ...

When I do a composer update, I have this error message :

    Your requirements could not be resolved to an installable set of packages.

    Problem 1
    - Installation request for bower-asset/bootstrap-tokenfield ~0.12.1 -> satisfiable by bower-asset/bootstrap-tokenfield[v0.12.1].
    - bower-asset/bootstrap-tokenfield v0.12.1 requires bower-asset/bootstrap ~3.1.1 -> no matching package found.

I had a similar issue with bower because bootstrap-tokenfield requires bootstrap ~3.1.1 and I use bootstrap ~3.3.4, but bower asked me how to proceed and I choose to use the last version of bootstrap.

As I know that bootstrap-tokenfield works well with the last version of bootstrap (3.3.5), how can I do to resolve this issue ?

**Comment by francoispluchino** [comment]
Indeed, if Bower you asks to select a version, so, it will be a problem, because Composer (and so the plugin) does not support this feature. But according to the conditions of versions of your example, I do not think that's the problem.

Quelle version du plugin utilisez vous ?

**Comment by jonag** [comment]
I use the version 1.0.3, which seems to be the last.

But if I understand well how the definition of dependencies works, bootstrap-tokenfield requires bootstrap > 3.1.1 and < 3.2.0 and because I use bootstrap 3.3.x the dependency can't be satisfied ?

**Comment by francoispluchino** [comment]
Sorry, I read wrong... yes this is the problem, your dependency is using a version prior to 3.2, then you will want get the 3.3 version. So there is a conflict. Bower manages conflicts, which is not the case for Composer. The only solution is to update `bootstrap-tokenfield` or use the 3.2 version.

**Comment by jonag** [comment]
Ok, merci. I will try to fork the repository to update the dependency or continue to use Bower for the moment.

**Comment by gwelr** [comment]
Just for the information, I faced this issue:
- run composer with bowser-assets requirements before installing the plugin,
- install the plugin
- run composer with bowser-assets requirements 
=> got the error. 
I solved the issue by deleting everything under the vendor/ folder, running composer clearcache and then composer install. Bootstrap 3.1.1 was correctly installed. 

Other option when you need a higher version of bootstrap is to fork the bootstrap-tokenfield github repository (the project seems to be no longer maintained), update the bower.json file and put "3.*" for bootstrap version requirements, register the fork with bower and then use that new package  in  your project dependencies. 

My 2 cents

**Comment by gwelr** [comment]
This is my fork of the bootstrap-tokenfield project with bootstrap dependencies fixed:
https://github.com/i-logs/bootstrap-tokenfield
Add the following line in your composer.json file to use it instead of bootstrap-tokenfield: 
```json
"bower-asset/bootstrap-tokenfield-ilogs":"0.12.1",
```
