### ISSUE TITLE
Getting undefined variable:config expection while trying to install asset plugin

### ISSUE THREAD

**Issue by semir-karic** [francoispluchino/composer-asset-plugin#148]
I don't know if it's the related to the plugin or my composer, but when I try to install composer asset plugin, I get 
[ErrorException]
Undefined variable: config

**Comment by francoispluchino** [comment]
Do you use the last `dev` version of Composer? And the last `stable` version of this plugin?

**Comment by semir-karic** [comment]
Tried updating composer and got it to install the plugin but now i get error
[ErrorException]
  Argument 1 passed to
Fxp\Composer\AssetPlugin\Repository\BowerRepository::createVcsRepositoryConfig()
must be of the t
  ype array, null given, called in
/root/.composer/vendor/fxp/composer-asset-plugin/Repository/AbstractAssetsRepository.
  php on line 136 and defined

while trying to create a yii2 project with composer using the following cmd:

composer create-project --prefer-dist yiisoft/yii2-app-basic basic


On Sun, Sep 20, 2015 at 6:56 PM, François Pluchino <notifications@github.com

**Comment by Stevad** [comment]
I have the same issue as @semir-karic. Clear install of composer. Update composer to latest version. And then - composer global require "fxp/composer-asset-plugin:~1.0.3".
And while installing project (I use Yii2 Advanced version), I've got the same error.
What we are doing wrong?

**Comment by digitalstaub** [comment]
same problem

**Comment by francoispluchino** [comment]
@samdark, @cebe, Do you have the same error with your framework?

**Comment by VincentQue** [comment]
same problem

 [ErrorException]
  Argument 1 passed to Fxp\Composer\AssetPlugin\Repository\BowerRepository:
  :createVcsRepositoryConfig() must be of the type array, null given, calle
  d in /Users/Vincent/.composer/vendor/fxp/composer-asset-plugin/Repository/
  AbstractAssetsRepository.php on line 136 and defined

**Comment by jacekm** [comment]
Confirm, the same problem during installing Yii2 App Advanced

**Comment by agungsijawir** [comment]
@francoispluchino @snickom found the issue [here](https://github.com/yiisoft/yii2/issues/9737#issuecomment-141812014). Seems the error not from this plugin, but RobinHerbots/jquery.inputmask. 

Need to wait until his PR merged and test it again.

**Comment by francoispluchino** [comment]
I just do the test for `yiisoft/yii2-app-advanced`, and it's OK.

```
$ composer create-project yiisoft/yii2-app-advanced . 2.0.6
Installing yiisoft/yii2-app-advanced (2.0.6)
  - Installing yiisoft/yii2-app-advanced (2.0.6)
    Downloading: 100%

Created project in .
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing yiisoft/yii2-composer (2.0.3)
    Downloading: 100%

  - Installing ezyang/htmlpurifier (v4.6.0)
    Downloading: 100%

  - Installing cebe/markdown (1.1.0)
    Downloading: 100%

  - Installing bower-asset/jquery (2.1.4)
    Downloading: 100%

  - Installing bower-asset/jquery.inputmask (3.1.63)
    Downloading: 100%

  - Installing bower-asset/punycode (v1.3.2)
    Downloading: 100%

  - Installing bower-asset/yii2-pjax (v2.0.4)
    Downloading: 100%

  - Installing yiisoft/yii2 (2.0.6)
    Downloading: 100%

  - Installing swiftmailer/swiftmailer (v5.4.1)
    Downloading: 100%

  - Installing yiisoft/yii2-swiftmailer (2.0.4)
    Downloading: 100%

  - Installing yiisoft/yii2-codeception (2.0.4)
    Downloading: 100%

  - Installing bower-asset/bootstrap (v3.3.5)
    Downloading: 100%

  - Installing yiisoft/yii2-bootstrap (2.0.4)
    Downloading: 100%

  - Installing yiisoft/yii2-debug (2.0.5)
    Downloading: 100%

  - Installing bower-asset/typeahead.js (v0.10.5)
    Downloading: 100%

  - Installing phpspec/php-diff (v1.0.2)
    Downloading: 100%

  - Installing yiisoft/yii2-gii (2.0.4)
    Downloading: 100%

  - Installing fzaninotto/faker (v1.5.0)
    Downloading: 100%

  - Installing yiisoft/yii2-faker (2.0.3)
    Downloading: 100%

Writing lock file
Generating autoload files
```

**Comment by francoispluchino** [comment]
@agungsijawir Thanks.

**Comment by agungsijawir** [comment]
yes, my pleasure @francoispluchino 
thank you for the cooperation

**Comment by shahidkarimi** [comment]
Undefined property: Fxp\Composer\AssetPlugin\Repository\BowerRepository::$repoConfig

How to fix this?
windows 10

**Comment by francoispluchino** [comment]
Version?

**Comment by shahidkarimi** [comment]
`Composer version 1.4-dev (78d81cc4734e5e50496df070671efc090517152e)`
@francoispluchino

**Comment by shahidkarimi** [comment]
`composer self-updating` works! @francoispluchino

**Comment by francoispluchino** [comment]
Perfect!
