### ISSUE TITLE
Fork in private repository

### ISSUE THREAD

**Issue by llfm** [francoispluchino/composer-asset-plugin#149]
Hello,

The following structure should work (I'm missing some information in the docs)?
>  Root
> `composer.json` has a private repository (a forked one)

> The forked one
> `composer.json` has a private asset repository (a forked one)

```json
...
"require": {
  "bower-asset/my-repo": "1.0.0"
},
"extra": {
  "asset-directories": [
    {
      "type": "vcs",
      "url": "xxxx:repo/my-repo.git",
      "name": "bower-asset/my-repo",
    }
  ]
}
```

The repo `my-repo` is a published package, but I want my version of it.
Composer understands it and get my forked version, does this plugin do it too?

**Comment by francoispluchino** [comment]
Yes you can use your forked repo. You must create and used a new branch for example.

```json
{
    "require": {
        "bower-asset/my-repo": "dev-my-new-branch"
    },
    "extra": {
        "asset-directories": [
            {
                "type": "vcs",
                "url": "xxxx:repo/my-repo.git",
                "name": "bower-asset/my-repo",
            }
        ]
    }
}
```

**Comment by llfm** [comment]
Thanks for the response. Actually, I miss the `bower-vcs` and the information that composer doesn't resolve repositories recursively.
