### ISSUE TITLE
post-install hook

### ISSUE THREAD

**Issue by bashilbers** [francoispluchino/composer-asset-plugin#153]
Hey,

Not really a bug, but I was wondering why there isn't a option to specify a post-install hook so I can just run composer install/update once instead of 2 times (composer-asset-plugin) needs to installed first else the bower packages can't be found.

Thoughts?

**Comment by francoispluchino** [comment]
Alas, it is a 'normal' behavior... and a limitation of the solver SAT of Composer. You will find all the details in the PR for Composer, see the issue #7.
