### ISSUE TITLE
Support for .npmignore file?

### ISSUE THREAD

**Issue by holtkamp** [francoispluchino/composer-asset-plugin#155]
UPDATE: still investigating, the ```bower.json``` approach now also starts throwing the update warning, any idea how to overcome this warning?

ORIGINAL DESCRIPTION:
The [documentation states](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md#enable-manually-the-deleting-of-the-ignore-files-for-npm) that NPM ```package.json``` files do not have an ```ignore``` section, which is correct. However, they *do* [offer a ```.npmignore``` file](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package). Is this supported by the Composer Asset Plugin?

**Rationale**
The reason why I am asking: when using a ```package.json``` to include assets like stylesheets which are developed in a separate project, I (apparently) have to specifically indicate which files have to be deleted in my own ```composer.json```: 

```
"extra": {
	"asset-ignore-files": {
		"npm-asset/project-web-themes": [
			"!dist/*",
		]
}
```

Only each update now results in a warning from composer, which halts the update process and requires the user to provide some input: 

```
- Updating npm-asset/project-web-themes (v0.0.3 => v0.0.4) 
    The package has modified files:
    D .gitignore
    D .npmignore
    D Gruntfile.js
    D README.md
    D XYZ.ext
-10 more files modified, choose "v" to view the full list
    Discard changes [y,n,v,d,?]?
```

When using a ```bower.json``` file with similar content as the NPM ```package.json``` and an additional  ```ignore``` section, this warning does NOT occur and seems therefore the preferred approach. Only this now leaves me with:
- an additional ```bower.json``` in the assets project
- a maintenance effort in the projects ```composer.json``` to make sure all unneeded asset files are deleted after installation

Not a big issue, but support for the ```.npmignore``` file would be nice, or am I misunderstanding the way this file should be interpreted?

**Comment by francoispluchino** [comment]
No, it's not supported by this plugin.

But for your problem, you can use the flag `--prefer-dist`. A zip archive will be downloaded instead of using GIT (remove your vendor directory before).

**Comment by holtkamp** [comment]
Well, tried the ```--prefer-dist``` flag, but still the warning appears when upgrading a version of a bower-asset

For now the only solution seems to instruct Composer to discard the changes:
http://stackoverflow.com/questions/13613619/how-to-avoid-composer-discard-changes-message?lq=1

This only works when using the ```--no-interaction``` flag:
```composer update -vvv --no-interaction```

**Context**
Note that this specific bower-asset is hosted at a private BitBucket repository. The ```bower.json``` file contains a section to indicate everything except 'dist' folder should be ignored:

```
  "ignore": [
    "*",
    "**/.*",
    "!/dist/**",
    "!/CHANGELOG.*",
    "!/LICENSE.*",
    "!/README.*"
  ]
```

You state "a zip archive will be downloaded", but will this also work for BitBucket? [It seems to have a different pattern for locating the ZIP archives than GitHub uses](
http://stackoverflow.com/questions/13044749/bitbucket-download-source-as-zip). Just to be clear, the ```dist``` folder should not contain a .zip archive, right?

It seems currently complete repo is being cloned.

**Comment by francoispluchino** [comment]
You must remove the package folder before. Otherwise, Composer will use always the GIT format.

And yes, a zip will be downloaded, see https://github.com/composer/composer/blob/master/src/Composer/Repository/Vcs/GitBitbucketDriver.php#L77.

**Comment by holtkamp** [comment]
Sorry for misunderstanding, but what do you mean with "You must remove the package folder before."? From where? See below, I use a complete clean install...

I try to understand it because it seems to be the source of the problem: "Composer will use always the GIT format", this seems to occur.

Instead of "downloading", composer keeps cloning / checking out the GIT repository, when performing a clean installation:

```
rm composer.lock && rm -rf public && rm -rf vendor
> composer install --prefer-dist

Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing bower-asset/project-name-themes (v0.1.4)       
    Cloning 3d990509af133d15a505bfae438b966cdSHA-sum
```

While installing other Bower assets clearly indicates it **downloads** instead of **clones**:

```
 - Installing bower-asset/bootstrap-css (2.3.2)
    Downloading: 100%         

  - Installing bower-asset/chartist (v0.9.4)
    Downloading: 100%         

  - Installing bower-asset/jquery (2.1.4)
    Downloading: 100%         

  - Installing bower-asset/chosen (v1.4.2)
    Downloading: 100%         

  - Installing bower-asset/clipboard (v1.4.2)
    Downloading: 100%         

  - Installing bower-asset/datatables (1.10.9)
    Downloading: 100%    
```

Note that manually downloading the ZIP using the tag name works:

https://bitbucket.org/organizationName/project-name-themes/get/v0.1.4.zip

BitBucket also properly recognizes the tagged versions, which use semantic versioning

**Comment by holtkamp** [comment]
Ok, spent some more time on this and I really think this is an issue with BitBucket-support. I created two repositories with equal content on both GitHub and BitBucket (GitHub has a 0.1.1 tag because of a mistake when creating the repo, but that should not matter for this test). Results below.

**Test repository on [GitHub](https://github.com/holtkamp/composer-asset-plugin-test)**
```
composer update -vv --prefer-dist 
Adding VCS repository git@github.com:holtkamp/composer-asset-plugin-test.git
Loading composer repositories with package information
Updating dependencies (including require-dev)
Reading bower.json of bower-asset/composer-asset-plugin-test (v0.1.1)
Importing tag v0.1.1 (0.1.1.0)
Reading bower.json of bower-asset/composer-asset-plugin-test (v0.1.0)
Importing tag v0.1.0 (0.1.0.0)
Analyzed 71 packages to resolve dependencies
Analyzed 71 rules to resolve dependencies
  - Installing bower-asset/composer-asset-plugin-test (v0.1.1)
    Downloading: 100%         
    Extracting archive

    REASON: Required by root: Install command rule (install bower-asset/composer-asset-plugin-test v0.1.1|install bower-asset/composer-asset-plugin-test v0.1.0)

Writing lock file
Generating autoload files
```

**Test repository on [BitBucket](https://bitbucket.org/holtkamp/composer-asset-plugin-test)**
```
composer update -vv --prefer-dist 
Adding VCS repository git@bitbucket.org:holtkamp/composer-asset-plugin-test.git
Loading composer repositories with package information
Updating dependencies (including require-dev)
Reading bower.json of bower-asset/composer-asset-plugin-test (v0.1.0)
Importing tag v0.1.0 (0.1.0.0)
Analyzed 70 packages to resolve dependencies
Analyzed 70 rules to resolve dependencies
  - Installing bower-asset/composer-asset-plugin-test (v0.1.0)
    Cloning 735ed903d8d27b4c2dee0091e6704d8cbc1b1571

    REASON: Required by root: Install command rule (install bower-asset/composer-asset-plugin-test v0.1.0)

Writing lock file
Generating autoload files
```

One can see that with GitHub the files are *installed* and with BitBucket the repository is *cloned*. The clone causes a GIT repository to appear in the installed assets folder. On the next update this will cause composer to generate the ```The package has modified files``` warning. I hope this clarifies my previous comments a bit...

**Comment by holtkamp** [comment]
ping ? See my last comment and examples, can somebody confirm this might be a bug with BitBucket repos?
