### ISSUE TITLE
Deprecated Notice 1.0.3

### ISSUE THREAD

**Issue by arydeoblo** [francoispluchino/composer-asset-plugin#159]
When i run php composer.phar global require "fxp/composer-asset-plugin:~1.0.3" it's generate this notice : 

Deprecation Notice: The Composer\Package\LinkConstraint\MultiConstraint class is deprecated, use Composer\Semver\Constraint\MultiConstraint instead. in phar:///usr/local/bin/composer/src/Composer/Package/LinkConstraint/MultiConstraint.php:17
Deprecation Notice: The Composer\Package\LinkConstraint\LinkConstraintInterface interface is deprecated, use Composer\Semver\Constraint\ConstraintInterface instead. in phar:///usr/local/bin/composer/src/Composer/Package/LinkConstraint/LinkConstraintInterface.php:17

**Comment by francoispluchino** [comment]
Thanks to see the issues before add a new duplicated issue :-). See #157, and PR #158.
