### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by DeOne4eg** [francoispluchino/composer-asset-plugin#160]
Deprecation Notice: The Composer\Package\LinkConstraint\MultiConstraint class is deprecated, use Composer\Semver\Constraint\MultiConstraint instead. in phar:///var/www/user/data/www/site.com/composer/src/Composer/Package/LinkConstraint/MultiConstraint.php:17
Deprecation Notice: The Composer\Package\LinkConstraint\LinkConstraintInterface interface is deprecated, use Composer\Semver\Constraint\ConstraintInterface instead. in phar:///var/www/user/data/www/site.com/composer/src/Composer/Package/LinkConstraint/LinkConstraintInterface.php:17

**Comment by francoispluchino** [comment]
Thanks to see the issues before add a new duplicated issue :-). See #157, #159, and PR #158.
