### ISSUE TITLE
Wrong parsing bower.json

### ISSUE THREAD

**Issue by ZAYEC77** [francoispluchino/composer-asset-plugin#162]
Hello, thank you so much for this plugin.
But I have some troubles with dependencies like this:
```json
  "dependencies": {
    "eve": "https://github.com/adobe-webplatform/eve.git#eef80ed"
  },
```
composer search package `DmitryBaranovskiy/eve` but it must looking for package `adobe-webplatform/eve`
https://github.com/DmitryBaranovskiy/raphael/blob/master/bower.json#L5

**Comment by francoispluchino** [comment]
What is your version of this plugin?

**Comment by ZAYEC77** [comment]
My global composer config:
`"fxp/composer-asset-plugin": "~1.0.3"`

**Comment by francoispluchino** [comment]
You can override the VCS config with the good package, see the doc [Overriding the config of a VCS Repository](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md#overriding-the-config-of-a-vcs-repository).

**Comment by ZAYEC77** [comment]
@francoispluchino thank You.
Have I override repository in own project composer.json or in package which I use in my project?

**Comment by francoispluchino** [comment]
Only in your root `composer.json` project.

**Comment by ZAYEC77** [comment]
Thankyou
