### ISSUE TITLE
assset-installer-paths broken with latest Composer version

### ISSUE THREAD

**Issue by samdark** [francoispluchino/composer-asset-plugin#164]
1. `composer self-update`.
2. `composer clear-cache`.
3. `composer create-project --prefer-dist yiisoft/yii2-app-basic delete_me`.
3. Got `\vendor\bower\bower-asset\*`.
4. `composer self-update 1.0.0-alpha11`.
5. `composer clear-cache`.
4. Got `\vendor\bower\*`.

Note extra `bower-asset` dir at step 3 which is not expected.

It worked well w/ alpha11: https://github.com/composer/composer/compare/1.0.0-alpha11...master

**Comment by steffendietz** [comment]
#165 adresses the same issue. But its more of a general question on how it's planned to proceed further. :)

**Comment by samdark** [comment]
https://github.com/composer/composer/commit/d98b134dc3ef7d5bd4b6e37c9621a811f8f1599d
