### ISSUE TITLE
Incomplete installations on Travis

### ISSUE THREAD

**Issue by mrclay** [francoispluchino/composer-asset-plugin#168]
We're installing on Travis-CI and notice that sometimes (probably rate limiting) assets are reported as installed (https://travis-ci.org/Elgg/Elgg/jobs/92918942#L261) but don't contain the build resources (https://travis-ci.org/Elgg/Elgg/jobs/92918942#L606 shows `dist/jquery.js` doesn't exist).

What can we do about this? If all files aren't installed, shouldn't composer report it as a failure?

**Comment by francoispluchino** [comment]
Because, you don't install the `stable` version of jquery. In `dev`, the `dist` folder doesn't exist. And this plugin downloads only the source.

**Comment by mrclay** [comment]
Our composer.json does have `"prefer-stable": true`. Is there really no way to use the `"^2.1.4"` syntax?

**Comment by mrclay** [comment]
Or does resolving that to a particular tag cost a bunch of GitHub API requests...

**Comment by francoispluchino** [comment]
I just did a test with:

```json
{
    "require": {
        "bower-asset/jquery": "^2.1.4"
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
}
```
Reslut:
```
$ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing bower-asset/jquery (2.1.4)
    Loading from cache

Writing lock file
Generating autoload files
```

The `stable` version with `dist` folder is downloaded.

For your question, you can see the FAQs [How to reduce the number of requests for getting the package definitions?](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/faqs.md#how-to-reduce-the-number-of-requests-for-getting-the-package-definitions).

**Comment by francoispluchino** [comment]
Same result with `--prefer-source` option:
```
$ composer install --prefer-source
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing bower-asset/jquery (2.1.4)
    Cloning 7751e69b615c6eca6f783a81e292a55725af6b85

Writing lock file
Generating autoload files
```

It is recommended that add the `--prefer-source` option in your Travis config.
