### ISSUE TITLE
Method VersionParser::parseLinks() does not exist anymore

### ISSUE THREAD

**Issue by xabbuh** [francoispluchino/composer-asset-plugin#169]
see the changes in Composer in composer/composer#4214 and composer/composer#4446 (refs composer/composer#4645)

**Comment by francoispluchino** [comment]
What is your version of this plugin? Because it's already updated with the last version.

**Comment by xabbuh** [comment]
@francoispluchino Sorry for the noise. I don't use the plugin myself and didn't look carefully enough at the code when looking at the referenced Composer issue.

**Comment by francoispluchino** [comment]
No problem!
