### ISSUE TITLE
Asset installer paths

### ISSUE THREAD

**Issue by psfpro** [francoispluchino/composer-asset-plugin#173]
On the project use the following settings: 
 ```json
  "extra": {
      "asset-installer-paths": {
          "npm-asset-library": "vendor/npm",
          "bower-asset-library": "vendor/bower"
      }
  }
  ```
The assets are downloaded to ``` vendor/bower/bower-asset ```

This is correct behavior?

**Comment by francoispluchino** [comment]
Update your composer asset plugin to `v1.1.1`.

**Comment by psfpro** [comment]
Thank you. Works.
