### ISSUE TITLE
Call to undefined method: VersionParser::parseLinks() 

### ISSUE THREAD

**Issue by littleguga** [francoispluchino/composer-asset-plugin#174]
Trying command:
``` composer global require "fxp/composer-asset-plugin:~1.0@dev" ```

Fatal error: Call to undefined method Fxp\Composer\AssetPlugin\Package\Version\V
ersionParser::parseLinks() in C:\Users\╘╕фюЁ\AppData\Roaming\Composer\vendor\fxp
\composer-asset-plugin\Repository\VcsPackageFilter.php on line 272

**Comment by francoispluchino** [comment]
Update your composer (`dev` version).

See #133, #135.

**Comment by littleguga** [comment]
@francoispluchino thank you. Sorry for the duplicate.

For others: [this method](https://github.com/francoispluchino/composer-asset-plugin/pull/133#issuecomment-145128571) helped me.
For the first step: go to C:\Users\[YOUR USER]\AppData\Roaming\ and delete "Composer" folder.

**Comment by francoispluchino** [comment]
Or simply use the option `--no-plugins` with `global update`.

```
$ composer global update --no-plugins
```
