### ISSUE TITLE
"asset-repositories" not working for required packages

### ISSUE THREAD

**Issue by unti1x** [francoispluchino/composer-asset-plugin#175]
In main composer.json required package `myvendor/frontend`, and in `frontend` package have this:

```json
...
    "bower-asset/suggestions-jquery": "dev-master"
  },
  "extra": {
      "asset-repositories": {
          "bower-asset/suggestions-jquery": {
              "type": "bower-vcs",
              "url": "https://github.com/hflabs/suggestions-jquery.git"
          }
      }
  },
...
 ```

On `composer update` package `suggestions-jquery` could not be found, but it works well, if required in main composer.json

**Comment by francoispluchino** [comment]
Because the `extra.asset-repositories` does work only in the root composer package (see the [doc](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/schema.md)).

**Comment by unti1x** [comment]
Oh, I see... Thanks.
