### ISSUE TITLE
Overriding repository dependencies

### ISSUE THREAD

**Issue by leandrogehlen** [francoispluchino/composer-asset-plugin#176]
I have follow situation:

project: **php-base** - composer.json: 
```js
{
    "name": "leandrogehlen/php-base",
    "description": "Base project",    
    "minimum-stability": "dev",
    "require": {
        "bower-asset/select2": "dev-master"
    },    
    "extra": {
        "asset-repositories": [
            {
                "type": "bower-github",
                "url": "https://github.com/leandrogehlen/select2.git",
                "name": "bower-asset/select2"
            }
        ]
    }
}
```
When i run composer, he install the correct assets from overrided repository in this case `https://github.com/leandrogehlen/select2.git`.

But if i use the `php-base` in other project like:

project: **php-other** - composer.json 
```js
{
    "name": "leandrogehlen/php-other",
    "description": "Other project",   
    "repositories": [{
        "type": "vcs",
        "url": "https://github.com/leandrogehlen/php-base"
    }],
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.4.0",
        "leandrogehlen/php-base": "dev-master"
    }
}
```
In this case the follow error occurs:
`bower-asset/select2 @dev -> no matching package found.`

Seems that is ignored extra configurations from **php-base**

**Comment by francoispluchino** [comment]
Because the `extra.asset-repositories` option is only used in your root composer package, see the [doc](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/schema.md#extraasset-repositories-root-only).

**Comment by leandrogehlen** [comment]
Ok, you are right
doc: 
> Repositories are not resolved recursively.

But doesn't necessary to implement this feature?

**Comment by francoispluchino** [comment]
This is a limitation of Composer, not the plugin ... But it might be possible to do it anyway, the same way that the plugin create VCS Repositories for dependencies with the direct links (but I still doubt).

**Comment by leandrogehlen** [comment]
Ok, thanks, but my problem is solved. I will add the configurations in main project like you told me.

**Comment by francoispluchino** [comment]
Ok, cool :)
