### ISSUE TITLE
composer asset plugin in require section ignores asset-installer-paths

### ISSUE THREAD

**Issue by nadar** [francoispluchino/composer-asset-plugin#178]
I may have read it somewhere already, but i just want to be sure this wont work:

```json
{
    "require": {
        "fxp/composer-asset-plugin" : "~1.1",
        "some_other_packges": " ...... "
    },
    "extra": {
        "asset-installer-paths": {
            "bower-asset-library": "vendor/bower"
        }
    }
}
```

Adding fxp/composer-asset-plugin in require section and define asset-installer-paths will ignore the extra options and copy the content to the default path "vendor/bower-asset"?

**Comment by francoispluchino** [comment]
Extra section is only used by the root Composer package.
