### ISSUE TITLE
 Class name must be a valid object or a string

### ISSUE THREAD

**Issue by supravatweb** [francoispluchino/composer-asset-plugin#180]
Why  getting the following error?

Creating migration...
PHP Fatal error:  Class name must be a valid object or a string in /var/www/html/demo_laravel/vendor/amsgames/laravel-shop/src/Commands/MigrationCommand.php on line 132
                                               
  [Symfony\Component\Debug\Exception\FatalErrorException]  
  Class name must be a valid object or a string

**Comment by francoispluchino** [comment]
Is it this plugin???

**Comment by cebe** [comment]
I very much doubt it...

**Comment by manoj-nandakumar** [comment]
Its not this plugin as i have also reproduced the same with a fresh installation of laravel.
check if u had properly named all the files that u have created. I had the same issue with a model file being named as *.phe instead of *.php

**Comment by cebe** [comment]
@francoispluchino I think this should be closed.

**Comment by manoj-nandakumar** [comment]
I Found a solution when i again tried to reproduce the error. Its mostly to do with the Entrust's incomplete documentation. The document says to add

  Zizaco\Entrust\EntrustServiceProvider::class

to the aliases arrayin config/app.php. Instead add this to the providers array.

Open config/app.php and find the providers key. Add EntrustServiceProvider to the array.

    ...
        Zizaco\Entrust\EntrustServiceProvider::class,
    ...

You can also add an alias to the list of class aliases in the same file.

    ...
        'Entrust' => Zizaco\Entrust\EntrustFacade::class,
    ...

**Comment by pagliaj** [comment]
I made the 2 updates to config/app.php and stil getting the same issue: 

PHP Fatal error:  Class 'Zizaco\Entrust\EntrustServiceProvider' not found in ./vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146

Any clues?

**Comment by francoispluchino** [comment]
This is not the plugin. Contact the support of Laravel.
