### ISSUE TITLE
Requirejs question

### ISSUE THREAD

**Issue by flodi** [francoispluchino/composer-asset-plugin#181]
This maybe is a n00b question, but I'm just learning bower right now.

I've all installed and working, composer maintain bower packages, and so on. I was using it including css and scripts directly from vendor/bower-asset/... when I noticed the requirejs folder.

This means that composer-asset-plugin create a requirejs-bower configuration? It does not seems the case, because I do not see a config.js file. What is the requirejs folder created?

Thank you very much.

**Comment by francoispluchino** [comment]
This plugin does not create a `requirejs-bower` config. It's maybe a used dependencies in your project.

**Comment by flodi** [comment]
Dho. Now it is clear :-(
