### ISSUE TITLE
case sensitive issue

### ISSUE THREAD

**Issue by oraluben** [francoispluchino/composer-asset-plugin#182]
Base64 and base64 are different package in NPM.
I found that composer-asset-plugin will only search package by lower case, so if I want Base64, I will get the wrong package.
I found this error when I was trying install webpack from NPM.

**Comment by francoispluchino** [comment]
See #70. It's the same problem for NPM, because Composer is not case sensitive.

You must override the package with your custom VCS Repository. Example with Boxer and boxer:

```json
{
    "require": {
        "bower-asset/boxer": "~3.3"
    },
    "extra": {
        "asset-repositories": [
            {
                "name": "bower-asset/boxer",
                "type": "bower-vcs",
                "url": "git://github.com/benplum/Boxer.git"
            }
        ]
    }
}
```

**Comment by oraluben** [comment]
Oh... Thanks for responding this duplicate issue. I will have a try.

**Comment by francoispluchino** [comment]
No problem :).
