### ISSUE TITLE
Plugin looking repo in lowercase

### ISSUE THREAD

**Issue by AstRonin** [francoispluchino/composer-asset-plugin#188]
In composer.json I write:
_"bower-asset/jQuery-contextMenu": "*",_ - https://github.com/swisnl/jQuery-contextMenu, last v2.1.0

but `composer update` brings other repo:
_Installing bower-asset/jquery-contextmenu (v0.5.2)_ - https://github.com/nitinuttarwar/jquery-contextmenu

**Comment by SDKiller** [comment]
@AstRonin 

https://github.com/francoispluchino/composer-asset-plugin/issues/70

**Comment by francoispluchino** [comment]
And precisely [this comment](https://github.com/francoispluchino/composer-asset-plugin/issues/70#issuecomment-64776637) for the solution.

**Comment by AstRonin** [comment]
Issue closed, [solution](https://github.com/francoispluchino/composer-asset-plugin/issues/70#issuecomment-64776637) works
