### ISSUE TITLE
"Your GitHub credentials are required to fetch private repository metadata"

### ISSUE THREAD

**Issue by nwoetzel** [francoispluchino/composer-asset-plugin#190]
with v1.1.1 of the plugin, when I call
`composer require npm-asset/less`
I get the following output:

> Using version ^2.6 for npm-asset/less
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your GitHub credentials are required to fetch private repository metadata (git://github.com/palmerabollo/joi-v1)
> Head to https://github.com/settings/tokens/new?scopes=repo&description=Composer+on+vagrant-ubuntu-trusty-64+2016-02-22+1056
> to retrieve a token. It will be stored in "/home/vagrant/.composer/auth.json" for future use by Composer.
> Token (hidden):

I am not quite sure, where the repository 'git://github.com/palmerabollo/joi-v1' is required.
There are no tags in that repo - could that be the reason why it requires the access token?
Is there a way to find out which package in the dependency tree of less might require it?
Am I doing something wrong or do I need to configure something differently (from the default)?

Any help would be appreciated, since I consider less essential for many of my projects.

**Comment by cebe** [comment]
I am not 100% sure what exactly caused this message but it may also be that you hit the github API rate limit and need to add your github account to be authenticated for a higher rate limit, see https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens

**Comment by nwoetzel** [comment]
No I just figured out, what the issue might be
when traversing the dependencies, it somehow sees that it needs to check
https://github.com/palmerabollo/joi-v1
but this repo does not exist (or is reaaly private to the user palmerabollo)
the correct one would be:
https://github.com/palmerabollo/joy-v1
which I can clone (note _joi_ vs _joy_)

I guess I have to manually overwrite the repo for the joi-v1 dependency to use https://github.com/palmerabollo/joy-v1?

**Comment by cebe** [comment]
looks like that is the problem, yes.

**Comment by palmerabollo** [comment]
I'm the owner of palmerabollo/joy-v1, let me see what could be happening because it should be public.

**Comment by cebe** [comment]
seems something in bower depends on `palmerabollo/joi-v1` instead of `palmerabollo/joy-v1`

**Comment by palmerabollo** [comment]
My fault. I've already renamed the repo to **joi-v1** in github, which is the correct name. The published npm module is all right (joi-v1 too). Sorry, guys.

**Comment by nwoetzel** [comment]
@palmerabollo 
Thanks

@others
Still, should there not be a failsafe in this plugin for those circumstances. It seems that there is no guarantee that modules listed at bower.io or npmjs.com are actually still present in their repositories. (Due to renaming, or deletion of repos or any other reason)
If this happens for assets that I directly require - I will just not use the asset. But for dependencies of dependencies, it is more likely to happen and not under the influence of the user and will potentially occur quite often the wider this plugin gets used.

**Comment by cebe** [comment]
if a dependency does no longer exist, the required package will no longer work and should release a new version with updated dependencies in bower.json

**Comment by nwoetzel** [comment]
@cebe 
I agree that it is the package maintainers or communities responsibility to maintain packages and dependencies.
Is the mechanism in this plugin slightly different than using the "native" package manager (meaning getting them from the repo urls instead of getting them from the package source?)
I guess it boils down to the question: Should there be a difference between
`npm install less`
and
`composer require npm-asset/less`
This is what I currently observe.

**Comment by nwoetzel** [comment]
I can fix `npm-asset/less` by manually adding vcs repos that cause errors as described here: https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md#overriding-the-config-of-a-vcs-repository

My composer.json looks like:
```
{
    "require": {
        "npm-asset/less":"^2.6"
    },
    "extra": {
        "asset-repositories": [
            {
                "type": "npm-vcs",
                "url": "https://github.com/peterolson/BigInteger.js",
                "name": "npm-asset/big-integer"
            },
            {
                "type": "npm-vcs",
                "url": "https://github.com/estools/estraverse.git",
                "name": "npm-asset/estraverse"
            }
        ]
    }
}
```
Just as a reference in case somebody else likes to install `npm-asset/less` with that plugin.

**Comment by nwoetzel** [comment]
Since my main problem is solved, I think the best is to close this issue.
Thanks for all your help, it is appreciated!
