### ISSUE TITLE
Composer keeps asking for hidden token

### ISSUE THREAD

**Issue by rubenheymans** [francoispluchino/composer-asset-plugin#196]
Everytime I update composer I have to enter a Token generated on github.
This happened after github.com/RamonSmit/Nestable.git became a private repo.
I removed all references to this repo.

[More info](http://stackoverflow.com/questions/35405128/composer-hidden-token)

**Comment by tcitworld** [comment]
Github no longer requires tokens to download releases.

**Comment by rubenheymans** [comment]
this didn't change anything, it's still asking for a token
