### ISSUE TITLE
Requested packages cannot be found... needs installation of plugin first ?

### ISSUE THREAD

**Issue by gossi** [francoispluchino/composer-asset-plugin#197]
Hi,

This is my require section:

```json
	"require" : {
		"fxp/composer-asset-plugin" : "~1.0",
		"bower-asset/bootstrap" : "~3",
		"bower-asset/font-awesome" : "~4",
		"bower-asset/swagger-ui" : "~2",
		"bower-asset/jquery-migrate" : "~1"
	}
```

When I run composer install, I get this following error messages:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/bootstrap could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package bower-asset/font-awesome could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package bower-asset/swagger-ui could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package bower-asset/jquery-migrate could not be found in any version, there may be a typo in the package name.
```

My workaround here is, to remove the `bower-asset` requirements from composer.json, run install, then readd them and run composer update. That way the plugin is installed first and then all assets. 

I'm wondering if that is the supposed way to do that? If not, what am I doing wrong? Thanks.

**Comment by francoispluchino** [comment]
Plugin must be installed global mode, not in project mode.

**Comment by gossi** [comment]
I guess there is no chance to make this available on a project level?

**Comment by francoispluchino** [comment]
No, alas..

**Comment by gossi** [comment]
I understand the composer plugin workflow doesn't allow this. Thanks for the help.

**Comment by brad-jones** [comment]
Could this be made clearer in the docs: https://github.com/francoispluchino/composer-asset-plugin/blob/master/Resources/doc/index.md

__Project scope installation__ suggests that this is possible when in fact it has to be installed globally.

**Comment by francoispluchino** [comment]
@brad-jones This section rather must be deleted.
