### ISSUE TITLE
Bower search problem

### ISSUE THREAD

**Issue by psfpro** [francoispluchino/composer-asset-plugin#203]
Bower search don't work now for packages like "jQuery-QueryBuilder"
https://bower.herokuapp.com/packages/search/jquery-querybuilder
Now we have "Package not found" response. Composer do strtolower for package names.

**Comment by francoispluchino** [comment]
Duplicate. See #70, and precisely [this comment](https://github.com/francoispluchino/composer-asset-plugin/issues/70#issuecomment-105926769).
