### ISSUE TITLE
Latest composer version breaks composer-asset-plugin

### ISSUE THREAD

**Issue by weph** [francoispluchino/composer-asset-plugin#207]
Apparently the latest composer version (cb8587cdade3cdbe00b8d6d2488458a2b6c0a592) has changed the signature of the whatProvides method:

`  [ErrorException]
  Declaration of Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository::whatProvides() should be compatible with Composer\Repository\ComposerRepository::whatProvides(Composer\DependencyResolver\Pool $pool, $name, $bypassFilters = false)`

**Comment by francoispluchino** [comment]
See PR #205 and #206.

**Comment by francoispluchino** [comment]
Fixed by #205.
