### ISSUE TITLE
Private Repository

### ISSUE THREAD

**Issue by itstueben** [francoispluchino/composer-asset-plugin#210]
It is possible to connect to a private repository?  (https://github.com/Hacklone/private-bower)
I dont want to connect directly to the svn Repo.

**Comment by francoispluchino** [comment]
Yes, of course. See the _Features included_ in the [readme](https://github.com/francoispluchino/composer-asset-plugin#features-include).

**Comment by itstueben** [comment]
Jeah kewl. But how? I only found the  "asset-repositories": ´but this is how to implement an VCS Repo directly. I want to connect to to private Bower Server! 
How can i solve that?

**Comment by francoispluchino** [comment]
This plugin only works with the direct private repositories (Git, GitHub, Git Bitbucket, Mercurial, Mercurial Bitbucket, SVN, Perforce), but not work with custom registries of repositories.

But it is simple to create an another registry for the private Bower registry (see [BowerRepository](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Repository/BowerRepository.php)).

Any help is welcome.

**Comment by itstueben** [comment]
I want to develop this PrivateRepo Class. I'm in the Final Steps. I need some help in the SVNDriver Class. I want to get some Information from composer.json . How can i get these Information in a function in the SVNDriver Class?

**Comment by francoispluchino** [comment]
What are the informations you want in the `composer.json` file?

**Comment by itstueben** [comment]
https://github.com/itstueben/composer-asset-plugin/blob/master/Repository/BowerPrivateRepository.php

I forked you Repo and add the new Private Repo File. But how can i access the composer.json options on line 34?

**Comment by itstueben** [comment]
I need the Information in the extra Section. For example "asset-svn-credentials"

**Comment by francoispluchino** [comment]
The credentials are managed by Composer, maybe that you want to talk of `svn-cache-credentials`.

To get the extra section in assets repository, you can add the `$extra` variable in `$config` variable (ex. `'composer-extra' => $extra`) in the [AssetPlugin::addRegistryRepositories](https://github.com/francoispluchino/composer-asset-plugin/blob/master/Util/AssetPlugin.php#L84) method.

**Comment by francoispluchino** [comment]
Added by #217.
