### ISSUE TITLE
The risk of running composer update as root

### ISSUE THREAD

**Issue by dbd5** [francoispluchino/composer-asset-plugin#213]
Hi;

When you attempt to run composer as root, you get the following error - which is OK;
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted;

In the last few days however, I have have had the following error repeatedly and each time, if I elevate privileges to root and run, the update occurs flawlessly. The question therefore is - is this really a package dependency problem?

Regards,

Adam

___

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package bower-asset/admin-lte could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package bower-asset/font-awesome could not be found in any version, there may be a typo in the package name.
  Problem 3
    - The requested package bower-asset/html5shiv could not be found in any version, there may be a typo in the package name.
  Problem 4
    - The requested package bower-asset/jquery-slimscroll could not be found in any version, there may be a typo in the package name.
  Problem 5
    - The requested package bower-asset/flot could not be found in any version, there may be a typo in the package name.
  Problem 6
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.x-dev requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - yiisoft/yii2 dev-master requires bower-asset/jquery.inputmask ~3.2.2 -> no matching package found.
    - yiisoft/yii2 2.0.7 requires bower-asset/jquery 2.2.*@stable | 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.6 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2 >=2.0.6 -> satisfiable by yiisoft/yii2[2.0.6, 2.0.7, dev-master, 2.0.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by cebe** [comment]
could it be that you have installed the composer asset plugin for the root user only?

**Comment by dbd5** [comment]
@cebe this is unlikely as I began to see this error only about 3 days ago and ordinarily I would not do composer update as root but I tried it as a work around because there are many stackoverflow comments on composer not updating correctly for regular user. How can I troubleshoot this?

**Comment by cebe** [comment]
1. update composer and the asset plugin to the latest version. Composer update as root, if you have a global install of it, but the asset plugin as normal user.
I would never run composer itself as root as you are mixing different environments then.
2. run composer update as normal user and see if it works.
3. if that did not work, remove composer.lock and vendor directory and run composer update again.

**Comment by dbd5** [comment]
Thanks, got it
