### ISSUE TITLE
Problem with composer update

### ISSUE THREAD

**Issue by xpunsterx** [francoispluchino/composer-asset-plugin#214]
I have:
```
Composer (v1.0.0)
Composer-asset-plugin (v1.1.3)
```
try to use:
`composer update`

and got the error:
```
[ReflectionException]                                                   
Class Fxp\Composer\AssetPlugin\Repository\NpmRepository does not exist  
                                                                                                                                                                       
[ErrorException]                                                                                       
Declaration of Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository::whatProvides() should be  
compatible with Composer\Repository\ComposerRepository::whatProvides(Composer\DependencyResolver\Poo  
l $pool, $name, $bypassFilters = false)  
```

**Comment by xpunsterx** [comment]
I found a solution:

`composer global update fxp/composer-asset-plugin --no-plugins`

it's works for me, but only in composer.json looks like:

```
{
"config": {
        "secure-http": false
    },
    "require": {
        "fxp/composer-asset-plugin": "dev-master"
    }
}

```

**Comment by cebe** [comment]
works fine for me with the following versions:

```
$ composer --version
Composer version 1.1-dev (89cfde051d70a02b9335fd79ce41bb7b3090a365) 2016-04-19 10:00:39
$ composer global show -i
fxp/composer-asset-plugin v1.1.3 NPM/Bower Dependency Manager for Composer
```

**Comment by snickom** [comment]
I got the following error message:
` [ErrorException]                                                             
  Declaration of Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository  
  ::whatProvides() should be compatible with Composer\Repository\ComposerRepo  
  sitory::whatProvides(Composer\DependencyResolver\Pool $pool, $name, $bypass  
  Filters = false) `

$ composer --version
Composer version 1.0.2 2016-04-21 12:30:18
$ composer global show -i
fxp/composer-asset-plugin v1.1.4 NPM/Bower Dependency Manager for Composer

**Comment by snickom** [comment]
After removing composer.lock and vendor folder everything works fine.

**Comment by francoispluchino** [comment]
Great!
