### ISSUE TITLE
strpos() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by iAchilles** [francoispluchino/composer-asset-plugin#218]
I updated composer-asset-plugin to v 1.1.4 and now I can't use composer update. 
Everytime I have the Exception:
[ErrorException]                                        
  strpos() expects parameter 1 to be string, array given  
                                                          

Exception trace:
 () at /home/igor/.composer/vendor/fxp/composer-asset-plugin/Converter/NpmPackageUtil.php:72
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 strpos() at /home/igor/.composer/vendor/fxp/composer-asset-plugin/Converter/NpmPackageUtil.php:72
 Fxp\Composer\AssetPlugin\Converter\NpmPackageUtil::convertDist() at /home/igor/.composer/vendor/fxp/composer-asset-plugin/Converter/NpmPackageConverter.php:53
 Fxp\Composer\AssetPlugin\Converter\NpmPackageConverter->Fxp\Composer\AssetPlugin\Converter\{closure}() at /home/igor/.composer/vendor/fxp/composer-asset-plugin/Converter/PackageUtil.php:162
 Fxp\Composer\AssetPlugin\Converter\PackageUtil::convertArrayKey() at /home/igor/.composer/vendor/fxp/composer-asset-plugin/Converter/AbstractPackageConverter.php:93
 Fxp\Composer\AssetPlugin\Converter\AbstractPackageConverter->convertKey() at /home/igor/.composer/vendor/fxp/composer-asset-plugin/Converter/AbstractPackageConverter.php:66
 Fxp\Composer\AssetPlugin\Converter\AbstractPackageConverter->convertData() at /home/igor/.composer/vendor/fxp/composer-asset-plugin/Converter/AbstractPackageConverter.php:47
 Fxp\Composer\AssetPlugin\Converter\AbstractPackageConverter->convert() at /home/igor/.composer/vendor/fxp/composer-asset-plugin/Repository/NpmRepository.php:132
 Fxp\Composer\AssetPlugin\Repository\NpmRepository->createArrayRepositoryConfig() at /home/igor/.composer/vendor/fxp/composer-asset-plugin/Repository/NpmRepository.php:79
 Fxp\Composer\AssetPlugin\Repository\NpmRepository->createVcsRepositoryConfig() at /home/igor/.composer/vendor/fxp/composer-asset-plugin/Repository/AbstractAssetsRepository.php:136
 Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:204
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:193
 Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:161
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:273
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromJobs() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/RuleSetGenerator.php:324
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Solver.php:214
 Composer\DependencyResolver\Solver->solve() at phar:///usr/local/bin/composer/src/Composer/Installer.php:502
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:228
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:134
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:189
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:24

I think it because of this commit:
https://github.com/francoispluchino/composer-asset-plugin/commit/a70e3d1db89d37712ce939a4eb1a71470ab8d496

**Comment by francoispluchino** [comment]
See #216.

**Comment by francoispluchino** [comment]
Fixed by #216.
