### ISSUE TITLE
composer require bower-asset/backbone.marionette: Could not parse version constraint <=1.3.x: Invalid version string "1.3.x"

### ISSUE THREAD

**Issue by mmlado** [francoispluchino/composer-asset-plugin#221]
We're getting error: Could not parse version constraint <=1.3.x: Invalid version string "1.3.x" when trying to install bower-asset/backbone.marionette
When looking at marionette source https://github.com/marionettejs/backbone.marionette/blob/master/bower.json looks like they changed the dependencies to show: 
"backbone": "1.0.0 - 1.3.x",
Looking at: Converter/SemverConverter.php
It looks like the x is only converted when the version number starts with ~ character, but it seams this will be converted to >=1.0.0,<=1.3.x only which is not recognized further in the code.
Hope this helps and it will be resolved quickly.

**Comment by francoispluchino** [comment]
Any PR is welcome.
