### ISSUE TITLE
Requires in Packagist

### ISSUE THREAD

**Issue by jasonrichardsmith** [francoispluchino/composer-asset-plugin#87]
I am creating a new repo that relies heavily on your loader.

Everything seemed to work fine in the root, when I was developing my project, but the plugin does not seem to be able to recognize in my packagist package.

https://packagist.org/packages/mongular/mongular

**Comment by francoispluchino** [comment]
The plugin must be installed in global mode (not in the `require` section in your composer.json project).

```bash
$ composer global require fxp/compaser-asset-plugin:@dev
```

In your composer.json project, you must added the `@dev` flag for each dependencies that use the `dev-master` version, or put the `minimum-stability` option to `dev` (it's the standard behavior of Composer).

**Comment by jasonrichardsmith** [comment]
Thank you!  As a heads up, from your input I created these install instructions which seem to work fine for  me.
https://github.com/jasonrichardsmith/mongular/wiki/Installation
