### ISSUE TITLE
Composer\Repository\Repository SecurityException

### ISSUE THREAD

**Issue by harshitj2005** [francoispluchino/composer-asset-plugin#89]
hi,

i have been trying to use yii2 framework by installing it through composer which require to use composer-asset-plugin. i have used the command composer global require "fxp/composer-asset-plugin:1.0.0-beta4" but its genetating this error Composer\Repository\Repository SecurityException
The contents of http://packagist.org/p/fxp/composer-asset-plugin$some no.json do not match its signature.
   This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.

have tried all possible way to solve it but cant find a solution.

solutions tried
composer config -g github-oauth.github.com <oauthtoken>
syntax error

composer config -ge adding lines 
"repositories": {
        "packagist": { "url": "https://packagist.org", "type": "composer" }
    }

but still same problem.

thanks in advance.

**Comment by francoispluchino** [comment]
Check your PHP configuration (open ssl, because Composer uses HTTP and not HTTPS).

**Example with Windows 8.1 x64 and PHP 5.6:**

```
C:\>composer global require fxp/composer-asset-plugin:1.0.0-beta4
Changed current directory to C:/Users/francois.pluchino/AppData/Roaming/Composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing fxp/composer-asset-plugin (v1.0.0-beta4)
    Downloading 100%

Writing lock file
Generating autoload files
```

**Comment by harshitj2005** [comment]
my PC config are windows 7 64bit and php is  5.4.27
and the ssl config is 

OpenSSL support	enabled
OpenSSL Library Version	OpenSSL 0.9.8y 5 Feb 2013
OpenSSL Header Version	OpenSSL 0.9.8y 5 Feb 2013

so tell me whether my PC is can support to this or not.?

**Comment by francoispluchino** [comment]
Is that OpenSSL is enabled in your `php.ini` file?

```
extension=php_openssl.dll
```

**Comment by harshitj2005** [comment]
yes...

**Comment by francoispluchino** [comment]
I think it's best to ask directly to the lead developers of Composer. See the issues composer/composer#3615 and composer/composer#3616.

**Comment by harshitj2005** [comment]
thanq for referencing to lead developers. lets hope they will be able to get my query solved.

**Comment by VijaySankhat** [comment]
[Composer\Repository\RepositorySecurityException]
  The contents of http://packagist.org/p/illuminate/pagination$47dc170ac3e8c4534e7d3ee39623a2cc8495821847914a59b1ec32dfc439a0c8.json do not match its signature
  . This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.



update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

**Comment by sadranyi** [comment]
try adding the snippet below to your composer.json file.
be sure to remove and add the quotes again this is an encoding issues :) 
hop it helps

“repositories”: {
“packagist”: { “url”: “https://packagist.org”, “type”: “composer” }
}

**Comment by johndan102** [comment]
@sadranyi  Your solution solved my challenge. Thanks a lot :)

**Comment by sadranyi** [comment]
Welcome

**Comment by nirajkmr** [comment]
{
  "require": {
    "nikic/fast-route": "^1.2",
    "facebook/graph-sdk": "^5.5",
 },
  
  "repositories": {
 "packagist": { "url":  "https://packagist.org",  "type":  "composer" }
}

}

**Comment by francoispluchino** [comment]
@nirajkmr Your example does not concern this plugin... In addition, I just tested your example with and without the addition of the Packagist repository, and with the latest stable versions, everything works fine.
