### ISSUE TITLE
'.' in package name not working

### ISSUE THREAD

**Issue by hashie5** [francoispluchino/composer-asset-plugin#90]
I tried installing circletype  
https://github.com/peterhry/CircleType  

"bower-asset/circletype.js": "@stable"  

But the plugin can't handle the `.` in the name

**Comment by francoispluchino** [comment]
CircleType has not a stable version, but only master branch.

You must use the dev flag `@dev`:

```json
{
    "require": {
        "bower-asset/circletype.js": "@dev"
    }
}
```

**Comment by francoispluchino** [comment]
Of course, you can use a `dev-master` version:

```json
{
    "require": {
        "bower-asset/circletype.js": "dev-master"
    }
}
```

**Comment by hashie5** [comment]
this is working! thanks
