### ISSUE TITLE
Tilde operator conversion

### ISSUE THREAD

**Issue by nkovacs** [francoispluchino/composer-asset-plugin#95]
According to [bower/npm](https://github.com/npm/node-semver#tilde-ranges-123-12-1)

~1 := >=1.0.0 <(1+1).0.0 := >=1.0.0 <2.0.0 (Same as 1.x)

But composer interprets ~1 as >=1 < 1.1

**Comment by nkovacs** [comment]
Also:
Bower: ~1.2 := >=1.2.0 <1.(2+1).0 := >=1.2.0 <1.3.0 (Same as 1.2.x)
Composer ~1.2 = >=1.2 < 2.0

**Comment by nkovacs** [comment]
I was using beta4, this has been fixed in master

**Comment by francoispluchino** [comment]
@nkovacs A stable version [1.0.0](https://github.com/francoispluchino/composer-asset-plugin/releases/tag/v1.0.0) is available.
