### ISSUE TITLE
Ignore files eror

### ISSUE THREAD

**Issue by mbman** [francoispluchino/composer-asset-plugin#98]
https://github.com/homerjam/angular-ui-router-anim-in-out/blob/master/bower.json shows the css and scss files from their directories not to be removed, but they're removed after install. If I set the ignore list to this, it works:

```
    "ignore": [
        "*",
        "!anim-in-out.js",
        "!css/",
        "!scss/"
    ],
```

**Comment by francoispluchino** [comment]
Fixed by #219.
